### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by treyhunner** [python/psf-community-resources#2]
MIT, BSD, CC0, Creative Commons Attribution? Probably doesn't much matter for these resources.

**Comment by KatherineMichel** [comment]
Looks like we have decided to use Creative Commons Attribution license: https://creativecommons.org/licenses/by/3.0/us/

**Comment by Mariatta** [comment]
The repo bears PSF name, maybe still worth checking with @VanL of what license to use. (IANAL)
This was also recently asked in DevGuide :) here is the response: https://github.com/python/devguide/issues/252#issuecomment-322926658

**Comment by KatherineMichel** [comment]
@Mariatta Thank you for that info!

**Comment by treyhunner** [comment]
Closed by #8! Thanks @KatherineMichel! :tada: :sparkles:
